#ifndef SENSOR_APP_COMMON_H
#define SENSOR_APP_COMMON_H

#define NODE_ID 2

#define DEFINED_TOS_AM_ADDRESS (NODE_ID)
#define TOS_NODE_ID (NODE_ID)

#define QUEUE_SIZE_SERIAL_DATA 255
#define QUEUE_SIZE_SERIAL_STATUS 32
#define QUEUE_SIZE_SERIAL_COMMAND 32

#define CONTROLLER_BUFFER_SIZE 2 //FOR NOW LARGEST BUFFER WE CAN HAVE IS 2

#define SENSOR_BUFFER_SIZE (CONTROLLER_BUFFER_SIZE)

#define RADIO_HISTORY_SIZE (CONTROLLER_BUFFER_SIZE)

#define NORMAL_RUN					0
#define TEST_SENSOR_AND_CONTROLLER	1
#define TEST_SERIAL_PORT			2

#define DEBUG_MODE NORMAL_RUN

//#define TRY_3_TIMES(x) (((call x)!=SUCCESS)?((call x)!=SUCCESS)?(call x):SUCCESS:SUCCESS)

#endif /* SENSOR_APP_COMMON_H */
